#!/usr/bin/python3
# SPDX-License-Identifier: MIT
# vim: set ts=4 sw=4 et :
#
# boot-data - show info from a boot-data file in a friendly way
#
# Author: Tim Bird <tim.bird@sony.com>
#
# Copyright 2026 Sony Group Corporation
#
# todo:
#   support diff_processes

import sys
import os
import stat
import re
from signal import signal, SIGPIPE, SIG_DFL
from subprocess import getstatusoutput
import subprocess
import boot_data_parser
from operator import itemgetter


VERSION = (0,5,0)

debug = False
verbose = False

# define some defaults
dur_thresh_percent = 0
duration_threshold = 10000
have_threshold = False
max_count = 10

def wprint(msg):
    sys.stderr.write("Warning: " + msg + '\n')
    sys.stderr.flush()

def eprint(msg):
    sys.stderr.write("Error: " + msg + '\n')
    sys.stderr.flush()

def error_out(msg, rcode=-1):
    eprint(msg)
    sys.exit(rcode)

def dprint(msg):
    global debug

    if debug:
        print("DEBUG: " + str(msg))

def vprint(msg):
    global verbose

    if verbose:
        print(msg)

def is_readable_file(filepath):
    real_path = os.path.realpath(filepath)
    if not os.path.isfile(real_path):
        return False
    return os.access(real_path, os.R_OK)

def usage():
    print("""Usage: boot-data [<file>] <cmd> [<item>] <options>
Look up information in a boot-data file (produced by
grab-boot-data.sh), or compare information from two
boot-data files.

Specify one or more boot-data files, and possibly a data item
name, along with one of the commands below:

In general, numbers that represent durations are in micro-seconds.
(So 54000 = 54ms, and 1300000 = 1.3s)

Commands:
  list         List the boot data items that can be shown
  show         Show an individual data item with it's value
  top          Show durations above a threshhold (default 10 ms)
  compare      Compare data items in two different files
  diff         Do a time-smart diff of two boot-data files

Options:
 -h, --help    Show this usage help
 -f <file>     Use this option to specify a second file for comparison
               commands to operate on
 -m <str>      Instead of specifying filenames, try to find a baseline
               find (and results file) that match the given string.
               ex: -m run-386421
 -d <ms>       Specify a threshold for the 'top' command, in milliseconds.
               Durations over the specified threshold will be shown
 -c <count>    Specify the max number of items to show for the 'top' command.
 -t <type>     Specify the type of items to show for the 'top' command.
               <type> can be 'initcall', 'region', 'systemd'.
 -p <percent>  Specify the duration threshold as a percent of baseline value.
               (e.g. for 10, only show values 10% different from baseline value)
 -v            Show verbose output
 --debug       Show debug information

Options for 'diff' command:
 -l            List the sections or data types that can be diff'ed
 -s <section>  Specify an individual section (or data element) to diff
""")
    sys.exit(0)

def show_version():
    print("boot-data - version %d.%d.%d" % VERSION)
    sys.exit(0)

# define some routines for argument handling
def get_opt_with_arg(arg):
    try:
        arg_pos = sys.argv.index(arg)
        var = sys.argv[arg_pos + 1]
        del sys.argv[arg_pos + 1]
        del sys.argv[arg_pos]
    except IndexError:
        error_out("Missing argument to '%s'. Use -h for help" % arg)

    return var

def get_boolean_opt(arg):
    if arg in sys.argv:
        sys.argv.remove(arg)
        return True
    else:
        return False

# put a wrapper around subprocess execution
# if in verbose_output mode,
#   output to my stdout while the subprocess is running
#   and return the empty string as output
# else use getstatusoutput to capture (and hide) the subprocess output.
# returns (status, output)
def execute_cmd(cmd, verbose_output=False):
    if verbose_output:
        try:
            result = subprocess.run(cmd, shell=True)
            status = result.returncode
            output = ""
        except subprocess.CalledProcessError as cp:
            status = cp.returncode
            output = cp.output

        return (status, output)
    else:
        return getstatusoutput(cmd)

def do_list(file1, item_type):
    global verbose

    print("""List of items (and item types) that can be shown:
== general data item types
  meta-data items
  initcalls, by function name (e.g. alsa_pcm_init)
  regions
  systemd items, by unit name (e.g. systemd-journal.service)
  config options, by name (e.g. CONFIG_BT)
""")

    if not file1:
        print("NOTE: Specify a boot-data file to see the list of items available in that file")
        sys.exit(0)

    print("== Specific data items in %s" % os.path.basename(file1))
    bd = boot_data_parser.parse_boot_data(None, file1)

    # show different data items
    if item_type == "meta" or item_type == None:
        print("Meta-data items:")
        metas = list(bd.available_metas())
        metas.sort()
        for name in metas:
            print("  " + name)

    if item_type == "initcall" or item_type == None:
        print("Initcalls:")
        ic_list = list(bd.initcalls.keys())
        ic_list.sort()
        for ic in ic_list:
            print("  " + ic)

    if item_type == "region" or item_type == None:
        print("Regions:")
        reg_list = list(bd.regions.keys())
        reg_list.sort()
        for region in reg_list:
            print("  " + region)

    if item_type == "systemd" or item_type == None:
        print("Systemd Items:")
        sd_list = list(bd.systemd_items.keys())
        sd_list.sort()
        for item in sd_list:
            print("  " + item)

    if verbose or item_type == "config":
        print("CONFIGS:")
        cname_list = list(bd.CONFIGS.keys())
        # cnames are short names (missing the 'CONFIG_' prefix)
        cname_list.sort()
        for cname in cname_list:
            print("  CONFIG_" + cname)
    else:
        if not item_type:
            print("NOTE: CONFIGS can be shown with -v (or -t config)")

    sys.exit(0)

def do_show(file1, options):
    items = options

    if not items:
        error_out("Missing name of data item to show (use -h for help)")

    bd = boot_data_parser.parse_boot_data(None, file1)

    if items[0] == "all":
        items = bd.available_items()
        items.sort()

    doing_multiple = False
    if len(items) > 1:
        doing_multiple = True

    for item in items:
        value = bd.get_any(item)
        if value=="**missing**":
            error_out("Could not find '%s' in boot data file %s" % (item, file1))

        if verbose or doing_multiple:
            print(item+"=", end='')
        print(value)

    sys.exit(0)

# returns a descriptor for the filename, or the empty string
def get_descriptor(filename):
    for desc in ["baseline", "results", "ref-value"]:
        if desc in filename:
            return desc
    return ""

def get_descr_str(prefix, desc):
    if desc:
        if prefix:
            return prefix + " (" + desc + ")"
        else:
            return "(" + desc + ")"
    else:
        return prefix

# units_str should be either 's', 'ms', 'us', or if it's a word
# it should start with a space ' seconds', ' msecs', ' usecs'
def get_dir_str(delta, units_str):
    if delta > 0:
        return "increased by %d%s" % (delta, units_str)
    elif delta < 0:
        return "decreased by %d%s" % (abs(delta), units_str)
    else:
        dir_str = ""

def do_compare(file1, file2, options):
    global dur_thresh_percent
    global duration_threshold
    global have_threshold

    items = options

    if not items:
        error_out("Missing name of data item to show (use -h for help)")

    bd1 = boot_data_parser.parse_boot_data(None, file1)
    bd2 = boot_data_parser.parse_boot_data(None, file2)

    if items[0] == "all":
        items = bd1.available_items()
        items.sort()

    # try to detect baseline vs results files
    # for that, eliminate symlinks, which might mask the filenames
    rfile1 = os.path.basename(os.path.realpath(file1))
    rfile2 = os.path.basename(os.path.realpath(file2))

    desc1 = get_descriptor(file1)
    desc2 = get_descriptor(file2)

    # try to guess baseline data set
    baseline = 0
    if desc1 == "baseline":
        baseline = 1

    if desc2 == "baseline" and not baseline:
        baseline = 1

    # treat ref value as baseline if baseline is not set
    if desc1 == "ref-value" and not baseline:
        baseline = 1
    if desc2 == "ref-value" and not baseline:
        baseline = 2

    # FIXTHIS - use baseline variable somewhere??

    desc1_str = get_descr_str("", desc1)
    desc2_str = get_descr_str("", desc2)

    doing_multiple = False
    if len(items) > 1:
        doing_multiple = True

    for item in items:
        value1 = bd1.get_any(item)
        value2 = bd2.get_any(item)

        if value1 == "**missing**" and value2 == "**missing**":
            error_out("Could not find '%s' in boot data files" % item)

        # determine whether to show data and direction
        show_data = True
        delta = 0
        try:
            value1 = int(value1)
            value2 = int(value2)
            delta = value2 - value1
        except:
            # not numbers means no direction possible
            delta = 0

        dir_str = get_dir_str(delta, " usecs")

        abs_delta = abs(delta)
        if abs_delta:
            if value1:
               delta_percent = float(abs_delta)/value1
               percent_str = f" ({delta_percent:.1%})"
            else:
               #percent_str = " (bajillion%)"
               percent_str = " (NaN%)"
        else:
            precent_str = ""

        # assume we can show direction
        if delta:
            baseline_value = value1
            if dur_thresh_percent:
                threshold_delta = int((baseline_value * dur_thresh_percent) / 100)
                threshold_low = max(baseline_value - threshold_delta, 0)
                threshold_high = baseline_value + threshold_delta
            else:
                threshold_delta = duration_threshold
                threshold_low = max(baseline_value - threshold_delta, 0)
                threshold_high = baseline_value + threshold_delta

            # if thresholds are specified, check for witholding output
            if have_threshold and (value2 > threshold_low and value2 < threshold_high):
                show_data = False

        # any delta under 3 microseconds is noise, IMNSHO
        if have_threshold and abs_delta < 3:
            show_data = False

        if show_data:
            print(f"-{item} 1 {desc1_str} = {value1}")
            print(f"+{item} 2 {desc2_str} = {value2}")
            if dir_str:
                print(f"  {item} {dir_str}{percent_str}")

    sys.exit(0)


def do_top(file1, item_type, options):
    global duration_threshold
    global dur_thresh_percent
    global max_count
    global have_threshold

    bd = boot_data_parser.parse_boot_data(None, file1)

    if dur_thresh_percent:
        error_out("Invalid option (-p). Threshold percent doesn't make sense for 'top'.")

    if item_type == "initcall":
        tuples = list(bd.initcalls.items())
    elif item_type == "region":
        tuples = list(bd.regions.items())
    elif item_type == "systemd":
        tuples = list(bd.systemd_items.items())
    elif item_type == None:
        # do them all
        tuples = list(bd.initcalls.items()) \
                    + list(bd.regions.items()) \
                    + list(bd.systemd_items.items())
    else:
        error_out("Invalid item_type '%s' in do_top()" % item_type)

    if have_threshold:
        filtered_tuples = [t for t in tuples if t[1] >= duration_threshold]
        tuples = filtered_tuples

    # sort by duration (which is tuple[1])
    items = sorted(tuples, key=itemgetter(1), reverse=True)

    items = items[:max_count]

    for item, value in items:
        print(f"{item:40} = {value:8} usecs")

    sys.exit(0)

def get_lines_1_2(bd1, bd2, sec_name):
    lines1 = bd1.get_section_block(sec_name)
    lines2 = bd2.get_section_block(sec_name)
    return (lines1, lines2)

# 'diff' notes:
# sections: Machine Info (obsolete)
# UPTIME
# GRAB-BOOT-DATA INFO
# Kernel Info,
# OS - text diff
# MEMORY
# DISK USAGE
# MOUNTS
# PROCESSES - order doesn't matter
# CORES - should be the same, CONFIG, SYSTEMD INFO,
# KERNEL MESSAGES - order not critical, start time not critical
#   delta matters, internal numbers might matter
class kline_class():
    def __init__(self, line, rest, index, ts_str, timestamp, delta):
        self.line = line  # full line
        self.rest = rest  # line without timestamp
        self.index = index
        self.ts_str = ts_str
        self.timestamp = timestamp
        self.delta = delta
        self.duration = 0
        self.used = False
        self.initcall = None

        self.set_match_str()
        self.id = self.match_str + " -i%s" % str(self.index)
        self.kline_match = None
        # number from 0 to 10, 0=no match
        self.match_confidence = 0

    def set_match_str(self):
        # to generate id, mask numbers and append index
        # do a series of substituions to mask numbers that might
        # change between runs (that we aren't interested in)

        # catch big numbers
        match_str = re.sub(r"0x[0-9a-fA-F]{8,}", "0XHxHxHxHx", self.rest)
        match_str = re.sub(r"[0-9]{8,}", "NnNnNnNn", match_str)
        match_str = re.sub(r"[0-9a-fA-F]{8,}", "HxHxHxHx", self.rest)

        # catch smaller numbers:
        match_str = re.sub(r"0x[0-9a-fA-F]{4,}", "0XHxHx", match_str)
        match_str = re.sub(r"[0-9]{4,}", "NnNn", match_str)

        # handle some strings specially
        if self.rest.startswith("Linux version"):
            match_str = "Linux version"

        # FIXTHIS - handle initcalls specially
        if self.rest.startswith("calling  "):
            if "+" in self.rest:
                initcall = self.rest[9:].split("+")[0]
            else:
                initcall = self.rest[9:].split(" ")[0]
            self.initcall = initcall
            match_str = "calling  " + initcall

        if self.rest.startswith("initcall "):
            if "+" in self.rest:
                initcall = self.rest[9:].split("+")[0]
            else:
                initcall = self.rest[9:].split(" ")[0]
            self.initcall = initcall
            match_str = "initcall " + initcall

        self.match_str = match_str

    def find_match(self, klines2):
        return None

def parse_kline(line):
    # returns timestamp in microseconds (int)
    ts_kline_regex = r"\[([0-9. ]+)\] (.*)"
    m = re.match(ts_kline_regex, line)
    if m:
        g = m.groups()
        ts_str = g[0]
        rest = g[1]
        try:
            timestamp = int(float(ts_str) * 1000000)
        except ValueError:
            timestamp = 0
    else:
        timestamp = 0
        rest = line

    return ts_str, timestamp, rest

# build data structures for diffing kernel message lines
# klines = map of list of klines, with kline.match_str being key
#   each value in klines is a list of msg lines that have that match_str
# kline_list = list of klines in print order
def get_klines(lines):
    klines = {}
    kline_list = []
    last_kline = None
    last_timestamp = 0
    for i in range(len(lines)):
        line = lines[i].strip()
        if not line:
            continue
        ts_str, timestamp, rest = parse_kline(line)
        if timestamp:
            delta = last_timestamp - timestamp
            last_timestamp = timestamp
        else:
            #wprint("Got a 0 timestamp on line %d: '%s" % (i, line))
            delta = 0
        kline = kline_class(line, rest, i, ts_str, timestamp, delta)
        if kline.match_str not in klines:
            klines[kline.match_str] = [kline]
        else:
            klines[kline.match_str].append(kline)
        kline_list.append(kline)
        if last_kline:
            last_kline.duration = abs(delta)
        last_kline = kline

    return (klines, kline_list)

# return the best match for kline1 out of klines2 messages
# returns (best_match, confidence)
# best_match can be None, confidence is in [0..10]
def get_best_kline_match(kline1, klines2, kline2_list):
    get_best_debug = False

    best = None
    confidence = 0

    # look for exact match on match_str
    matches = klines2.get(kline1.match_str, None)
    # matches should be sorted by index
    # find first unused one
    if matches:
        for candidate_kline in matches:
            if candidate_kline.used:
                continue
            best = candidate_kline
            confidence = 10
            return best, confidence

    # try searching whole kline2 space, with weaker match_strs
    # collect tuples (kline2, confidence)
    weak_matches = []
    no_num_match_str1 = re.sub("[0-9]","", kline1.match_str)
    early_match_str1 = no_num_match_str1[:20]
    earlier_match_str1 = early_match_str1[:10]
    first_match = False
    confidence = 0
    for kline2 in kline2_list:
        if kline2.used:
            continue
        no_num_match_str2 = re.sub("[0-9]","", kline2.match_str)
        early_match_str2 = no_num_match_str2[:20]
        earlier_match_str2 = early_match_str2[:10]
        if no_num_match_str1 == no_num_match_str2:
            if first_match:
                confidence = 9
            else:
                confidence = 8
            first_match = True
            weak_matches.append((kline2, confidence))
            continue
        if early_match_str1 == early_match_str2:
            if first_match:
                confidence = 6
            else:
                confidence = 5
            first_match = True
            weak_matches.append((kline2, confidence))
            continue
        if earlier_match_str1 == earlier_match_str2:
            if first_match:
                confidence = 3
            else:
                confidence = 2
            first_match = True
            weak_matches.append((kline2, confidence))

    # find the item with the highest confidence
    if weak_matches:
        weak_matches_sorted = sorted(weak_matches, key=itemgetter(1))
        best, confidence = weak_matches_sorted[-1]

    if get_best_debug:
        print("in get_best_kline_match")
        print(f"  {kline1.rest=}")
        print(f"  {kline1.match_str=}")
        if best:
            print(f"  {best.rest=}")
            print(f"  {best.match_str=}")
        else:
            print(f"  {best}")
        print(f"  {confidence=}")

    return best, confidence

def kmsg_show_line(kline1, kline2, index_delta, ts_delta, reason):
    debug_kmsg = False
    #debug_kmsg = True

    dmsg = ""
    delta1 = abs(float(kline1.delta) / 1000000)
    msg = kline1.rest
    # truncate msg to a fixed width
    MSG_WIDTH = 72
    if len(msg) > MSG_WIDTH:
        msg = msg[:MSG_WIDTH-2]+".."
    kline1_str = f"[{kline1.ts_str}] <{delta1:9.6f}> {msg}"
    dmsg += f"   {kline1.match_str=}\n"
    dmsg += "   line1 duration = %d\n" % kline1.duration
    dmsg += "   line1 delta = %d\n" % kline1.delta
    kline1.used = True
    if kline2:
        prefix = " "
        delta2 = abs(float(kline2.delta) / 1000000)
        pad = " " * max(100 - len(kline1_str), 1)
        suffix = f"{pad}[{kline2.ts_str}] <{delta2:9.6f}> d={ts_delta}\n"
        kline2.used = True
        dmsg += "   index delta = %d\n" % index_delta
        dmsg += "   timestamp delta = %d\n" % ts_delta
        dmsg += "   line2 duration = %d\n" % kline2.duration
        dmsg += "   line2 delta = %d\n" % kline2.delta
        dmsg += f"   {kline2.match_str=}\n"

    else:
        prefix = "-"
        suffix = "\n"

    dmsg += "   reason: %s\n" % reason
    if not debug_kmsg:
        dmsg = ""

    return prefix + kline1_str + suffix + dmsg


def diff_kmsg(bd1, bd2, desc1, desc2):
    global verbose

    lines1, lines2 = get_lines_1_2(bd1, bd2, "KERNEL MESSAGES")

    klines1, kline1_list = get_klines(lines1)
    klines2, kline2_list = get_klines(lines2)

    # build a list of output strings first, then intersperse
    #  unmatched items from klines2_list on output

    # output_tuples = [(kline1, out_str),...]
    output_tuples = []

    index_delta = 0
    last_index_delta = 0
    ts_delta = 0
    last_ts_delta = 0
    for kline1 in kline1_list:
        show_line = False
        if verbose:
            show_line = True
            reason = "debug"

        kline2, confidence = get_best_kline_match(kline1, klines2, kline2_list)
        if kline2:
            kline1.kline_match = kline2
            kline1.match_confidence = confidence
            kline2.used = True
            index_delta = kline2.index - kline1.index
            ts_delta = kline2.timestamp - kline1.timestamp

            # if lines shifted position, show them
            if index_delta != last_index_delta:
                #show_line = True
                #reason = "line shifted position"
                pass

            # if lines shifted delta by more than 5 usecs, show them
            last_index_delta = index_delta
            if abs(ts_delta != last_ts_delta) > 5:
                show_line = True
                reason = "line shifted delta"

            # if line shifted in delta, show it
            delta_delta = kline2.delta - kline1.delta
            if abs(delta_delta) > 200:
                show_line = True
                reason = "line changed delta"

            # if line shifted in duration, show it
            dur_delta = kline2.duration - kline1.duration
            if abs(dur_delta) > 200:
                show_line = True
                reason = "line changed duration"

            # other criteria?
        else:
            # show any unmatched lines
            show_line = True
            reason = "has no match"

        debug_kmsg = False
        if show_line:
            out_str = kmsg_show_line(kline1, kline2, index_delta, ts_delta, reason)
            output_tuples.append((kline1, out_str))

        # done with this kline1

    # build 'output', interspersing unused k2 lines into output_tuples
    output = ""
    i = 0
    j = 0
    k1_k2_timestamp = 0
    last_k2_timestamp = 0
    while i < len(output_tuples):
        kline1, out_str = output_tuples[i]

        # move to first unused kline2
        while j < len(kline2_list) and kline2_list[j].used:
            j += 1

        try:
            kline2 = kline2_list[j]
        except IndexError:
            kline2 = None

        # output from output_tuples or kline2_list?
        if kline1.kline_match:
            k1_k2_timestamp = kline1.kline_match.timestamp

        if kline2 and (kline2.timestamp < k1_k2_timestamp):
            # handle weirdness if the timestamps revert back in value
            # due to the early times patch
            if kline2.timestamp >= last_k2_timestamp:
                # format a '+' line with no k1 timestamp or delta data
                delta2 = abs(float(kline2.delta) / 1000000)
                msg = kline2.rest
                MSG_WIDTH=72
                if len(msg) > MSG_WIDTH:
                    msg = msg[:MSG_WIDTH-2]+".."
                part1 = f"                           {msg}"
                pad = " " * max(100 - len(part1), 1)
                part2 = f"{pad}[{kline2.ts_str}] <{delta2:9.6f}> d=n/a\n"
                out_str = "+" + part1 + part2

                last_k2_timestamp = kline2.timestamp
                #print(f"TRB: {out_str=}")
                kline2.used = True
                j += 1
            else:
                i += 1
                last_k2_timestamp = k1_k2_timestamp
        else:
            # use current out_str from output_tuples
            i += 1
            last_k2_timestamp = k1_k2_timestamp

        output += out_str
        #print(f"TRB: {out_str}", end="")

    if debug_kmsg:
        output += "some debug data:\n"

        output += "\n#######\nfile2 lines with duplicate match_strs\n"
        count_dup_match_str2 = 0
        unused_count = 0
        for klist in klines2.values():
            if len(klist) > 1:
                output += f"match_str={klist[0].match_str}\n"
                count_dup_match_str2 += 1
                for kline in klist:
                    if kline.used:
                        used_str = "   used "
                    else:
                        used_str = "*unused*"
                        unused_count += 1

                    output += f"  {used_str} {kline.index}: {kline.line}\n"
        output += f"{count_dup_match_str2=}\n"
        output += f"{unused_count=}\n"

    # report break
    report_break = '\n' + ("-" * 60) + "\n\n"
    output += report_break

    output += diff_initcalls(bd1, bd2, desc1, desc2)

    output += report_break

    output += diff_regions(bd1, bd2, desc1, desc2)

    return output

def diff_mem(bd1, bd2, desc1, desc2):
    #sec_name = "MEMORY"

    items = ["MEM_TOTAL", "MEM_USED"]

    desc1_str = get_descr_str("file1", desc1)
    desc2_str = get_descr_str("file2", desc2)

    header = f"--- {desc1_str}\n"
    header += f"+++ {desc2_str}\n"

    output = ""
    change_count = 0
    for item in items:
        value1 = int(bd1.get_meta(item))
        value2 = int(bd2.get_meta(item))
        if value1 != value2:
            change_count += 1
            output += f"-{item}={value1}\n"
            output += f"+{item}={value2}\n"
            delta = value2 - value1
            dir_str = get_dir_str(delta, "K")
            output += f"  {item} {dir_str}\n"


    if change_count == 0:
        output = "** No changes **"

    return output

# perform diff with external tool
def diff_ext(bd1, bd2, desc1, desc2, sec_name, ext_tool="diff -u"):
    global debug

    import tempfile

    lines1, lines2 = get_lines_1_2(bd1, bd2, sec_name)
    if lines1 == "**NO DATA**":
        msg = "Missing block data for section '%s' in %s file" % (sec_name, desc1)
        return msg

    if lines2 == "**NO DATA**":
        msg = "Missing block data for section '%s' in %s file" % (sec_name, desc2)
        return msg

    # write each block to a file, then process the files with the ext_tool
    block1 = "\n".join(lines1)
    block2 = "\n".join(lines2)

    with tempfile.NamedTemporaryFile(delete=False, mode="w+t", \
        encoding="utf-8", suffix=".txt") as fp1:
        fp1.write(block1)
        fp1.close()

    with tempfile.NamedTemporaryFile(delete=False, mode="w+t", \
        encoding="utf-8", suffix=".txt") as fp2:
        fp2.write(block2)
        fp2.close()

    cmd = f"{ext_tool} {fp1.name} {fp2.name}"
    (status, output) = execute_cmd(cmd)


    if desc1 and desc1 != desc2:
        output = output.replace(fp1.name, desc1)
    if desc2 and desc1 != desc2:
        output = output.replace(fp2.name, desc2)

    if debug:
        print(f"DEBUG: {fp1.name=}")
        print(f"DEBUG: {fp2.name=}")
        print("NOTICE!! - not deleting these temp files, you need to do so manually")
        print(output)
    else:
        os.unlink(fp1.name)
        os.unlink(fp2.name)

    # check for empty output (meaning no changes)
    if output.strip() == "":
        output = "** No changes **"

    return output

def diff_processes(bd1, bd2, desc1, desc2):
    lines1, lines2 = get_lines_1_2(bd1, bd2, "PROCESSES")

    output = "FIXTHIS - need to finish diff_processes()"
    return output

def diff_modules(bd1, bd2, desc1, desc2):
    #sec_name = "MODULES"

    output = ""
    mod1_names = list(bd1.modules.keys())
    if not mod1_names:
        output += "Warning: Missing data for MODULES section in file1\n"
    mod1_names.sort()
    # avoid index errors

    mod2_names = list(bd2.modules.keys())
    if not mod2_names:
        output += "Warning: Missing data for MODULES section in file2\n"
    mod2_names.sort()

    # if no data, don't show an empty table
    if (not mod1_names) and (not mod2_names):
        return output

    mod1_names.append("zzz**end**")
    mod2_names.append("zzz**end**")

    # gather data, then sort and display it (by longest duration?)
    # pick from one list, then the other, according to merge order
    i = 0
    j = 0
    output_tuples = []
    while i < len(mod1_names)-1 and j < len(mod2_names)-1:
        name1 = mod1_names[i]
        name2 = mod2_names[j]
        #print(f"{i=},{j=},{name1=},{name2=}")
        if name1 < name2:
            name = name1
            i += 1
            tuple1 = bd1.modules[name]
            if name in bd2.modules:
                tuple2 = bd2.modules[name]
            else:
                tuple2 = None

        if name1 == name2:
            name = name1
            i += 1
            j += 1
            tuple1 = bd1.modules[name]
            if name in bd2.modules:
                tuple2 = bd2.modules[name]
            else:
                tuple2 = None

        if name1 > name2:
            name = name2
            j += 1
            tuple2 = bd2.modules[name]
            if name in bd1.modules:
                tuple1 = bd1.modules[name]
            else:
                tuple1 = 0

        output_tuples.append((name, tuple1, tuple2))

    data = sorted(output_tuples, key=itemgetter(0))

    output += " Module                          Size              Used by\n"
    output += " =============================== =======           =======\n"
    for name, t1, t2 in data:
        if t1 and not t2:
            size1, usedby1 = t1
            output += "-%-30s %7s            %s" % (name, size1, usedby1)

        if not t1 and t2:
            size2, usedby2 = t2
            output += "+%-30s          %7s   %s" % (name, size2, usedby2)

        if t1 and t2:
            size1, usedby1 = t1
            size2, usedby2 = t2
            if size1 == size2:
                size_str = "%7s" % size1
            else:
                size_str = "%7s -> %s" % (size1, size2)
            if usedby1 == usedby2:
                usedby_str = usedby1
            else:
                usedby_str = "%s -> %s" % (usedby1, usedby2)
            output += " %-30s %-18s %s" % (name, size_str, usedby_str)

        output += "\n"

    return output


def diff_config(bd1, bd2, desc1, desc2):
    #sec_name = "CONFIG"

    desc1_str = get_descr_str("file1", desc1)
    desc2_str = get_descr_str("file2", desc2)
    header = f"--- {desc1_str}\n"
    header += f"+++ {desc2_str}\n"

    output = diff_ext(bd1, bd2, desc1, desc2, "CONFIG", "diffconfig")

    return header + output

def diff_systemd(bd1, bd2, desc1, desc2):
    #sec_name = "SYSTEMD INFO"

    # get data, sorted by name
    sd1_names = list(bd1.systemd_items.keys())
    sd1_names.sort()
    # avoid index errors
    sd1_names.append("zzz**end**")

    sd2_names = list(bd2.systemd_items.keys())
    sd2_names.sort()
    sd2_names.append("zzz**end**")

    # gather data, then sort and display it (by longest duration?)
    # pick from one list, then the other, according to merge order
    i = 0
    j = 0
    tuples = []
    while i < len(sd1_names)-1 and j < len(sd2_names)-1:
        name1 = sd1_names[i]
        name2 = sd2_names[j]
        #print(f"{i=},{j=},{name1=},{name2=}")
        if name1 < name2:
            name = name1
            i += 1
            value1 = bd1.systemd_items[name]
            if name in bd2.systemd_items:
                value2 = bd2.systemd_items[name]
                delta = value2 - value1
            else:
                value2 = 0
                delta = -value1

        if name1 == name2:
            name = name1
            i += 1
            j += 1
            value1 = bd1.systemd_items[name]
            if name in bd2.systemd_items:
                value2 = bd2.systemd_items[name]
                delta = value2 - value1
            else:
                value2 = 0
                delta = -value1

        if name1 > name2:
            name = name2
            j += 1
            value2 = bd2.systemd_items[name]
            if name in bd1.systemd_items:
                value1 = bd1.systemd_items[name]
                delta = value2 - value1
            else:
                value1 = 0
                delta = value2

        tuples.append((name, value1, value2, delta, abs(delta)))

    data = sorted(tuples, key=itemgetter(1), reverse=True)

    output  = "item                                     file1   file2   delta\n"
    output += "======================================== ======= ======= ===========\n"
    for name, v1, v2, delta, abs_delta  in data:
        if v1:
            v1 = "%7.3f" % (float(v1)/1000000)
        else:
            v1 = "----"

        if v2:
            v2 = "%7.3f" % (float(v2)/1000000)
        else:
            v2 = "----"

        fd = "%7.3f" % (float(delta)/1000000)

        if len(name)>38:
            name = name[:38]+".."

        note = " "
        if abs_delta > 50000:
          note = "!"
        output += "%-40s %7s %7s %7s %s secs" % (name, v1, v2, fd, note)
        output += "\n"

    return output

def diff_initcalls(bd1, bd2, desc1, desc2):
    # get data, sorted by name
    ic1_names = list(bd1.initcalls.keys())
    ic1_names.sort()
    ic1_names.append("zzz**end**")

    ic2_names = list(bd2.initcalls.keys())
    ic2_names.sort()
    ic2_names.append("zzz**end**")

    # gather data, then sort and display it (by longest duration?)
    # pick from one list, then the other, according to merge order
    i = 0
    j = 0
    tuples = []
    while i < len(ic1_names)-1 and j < len(ic2_names)-1:
        name1 = ic1_names[i]
        name2 = ic2_names[j]
        #print(f"{i=},{j=},{name1=},{name2=}")
        if name1 < name2:
            name = name1
            i += 1
            value1 = bd1.initcalls[name]
            if name in bd2.initcalls:
                value2 = bd2.initcalls[name]
                delta = value2 - value1
            else:
                value2 = -1
                delta = -value1

        if name1 == name2:
            name = name1
            i += 1
            j += 1
            value1 = bd1.initcalls[name]
            if name in bd2.initcalls:
                value2 = bd2.initcalls[name]
                delta = value2 - value1
            else:
                value2 = -1
                delta = -value1

        if name1 > name2:
            name = name2
            j += 1
            value2 = bd2.initcalls[name]
            if name in bd1.initcalls:
                value1 = bd1.initcalls[name]
                delta = values - value1
            else:
                value1 = -1
                delta = value2

        tuples.append((name, value1, value2, delta, abs(delta)))

    data = sorted(tuples, key=itemgetter(1), reverse=True)

    output = "Initcall table (omitting initcalls with duration 0 usecs)\n"
    output += "Highlight (with !) changed calls: over 10ms delta, or missing.\n"
    output += "Omit items with zeros or small deltas (< 3 usecs).\n\n"
    output += "initcall                              file1   file2   delta\n"
    output += "===================================== ======= ======= ===========\n"
    for name, v1, v2, delta, abs_delta  in data:
        note = " "
        if v1 == 0 and v2 == 0:
            continue

        if abs_delta < 3:
            continue

        if v1 == -1:
            v1 = "----"
            note = "!"
        if v2 == -1:
            v2 = "----"
            note = "!"

        # mark any change over 10ms
        if abs_delta > 10000:
            note = "!"

        output += "%-36s %7s %7s %7s %s usecs" % (name, v1, v2, delta, note)
        output += "\n"

    return output

def diff_regions(bd1, bd2, desc1, desc2):
    # get data, sorted by name
    reg1_names = list(bd1.regions.keys())
    reg1_names.sort()
    reg1_names.append("zzz**end**")

    reg2_names = list(bd2.regions.keys())
    reg2_names.sort()
    reg2_names.append("zzz**end**")

    # gather data, then sort and display it (by longest duration?)
    # pick from one list, then the other, according to merge order
    i = 0
    j = 0
    tuples = []
    while i < len(reg1_names)-1 and j < len(reg2_names)-1:
        name1 = reg1_names[i]
        name2 = reg2_names[j]
        #print(f"{i=},{j=},{name1=},{name2=}")
        if name1 < name2:
            name = name1
            i += 1
            value1 = bd1.regions[name]
            if name in bd2.regions:
                value2 = bd2.regions[name]
                delta = value2 - value1
            else:
                value2 = -1
                delta = -value1

        if name1 == name2:
            name = name1
            i += 1
            j += 1
            value1 = bd1.regions[name]
            if name in bd2.regions:
                value2 = bd2.regions[name]
                delta = value2 - value1
            else:
                value2 = -1
                delta = -value1

        if name1 > name2:
            name = name2
            j += 1
            value2 = bd2.regions[name]
            if name in bd1.regions:
                value1 = bd1.regions[name]
                delta = values - value1
            else:
                value1 = -1
                delta = value2

        tuples.append((name, value1, value2, delta, abs(delta)))

    data = sorted(tuples, key=itemgetter(1), reverse=True)

    output = "Region table (omitting regions with duration 0 usecs)\n"
    output += "Highlight (with !) changed durations: over 10ms delta, or missing.\n"
    output += "Omit items with zeros or small deltas (< 3 usecs).\n\n"
    output += "region                                file1   file2   delta\n"
    output += "===================================== ======= ======= ===========\n"
    for name, v1, v2, delta, abs_delta  in data:
        note = " "
        if v1 == 0 and v2 == 0:
            continue

        if abs_delta < 3:
            continue

        if v1 == -1:
            v1 = "----"
            note = "!"
        if v2 == -1:
            v2 = "----"
            note = "!"

        # mark any change over 10ms
        if abs_delta > 10000:
            note = "!"

        output += "%-36s %7s %7s %7s %s usecs" % (name, v1, v2, delta, note)
        output += "\n"

    return output


# section_prefs has the table of which diff to use per section:
# consisting of tuples like this:
#   (simple section name, section name, preferred diff method)
#
# diff methods:
#  text = text diff
#  diffconfig = diffconfig diff
#  num = numeric diff (possibly with thresholds)
#  process_diff = special process diff
#  systemd_diff = special systemd diff
#  kmsg_diff = special kernel message diff

section_prefs = {"uptime": ("UPTIME", "text"),
                 "gbd": ("GRAB-BOOT-DATA INFO", "text"),
                 "kernel": ("Kernel Info", "text"),
                 "os": ("OS", "text"),
                 "mem": ("MEMORY", "diff_mem"),
                 "disk": ("DISK USAGE", "text"),
                 "mounts": ("MOUNTS", "text"),
                 "modules": ("MODULES", "diff_modules"),
                 "processes": ("PROCESSES", "diff_processes"),
                 "cores": ("CORES", "text"),
                 "config": ("CONFIG", "diff_config"),
                 "systemd": ("SYSTEMD INFO", "diff_systemd"),
                 "kmsg": ("KERNEL MESSAGES", "diff_kmsg"),
                 "initcalls": ("KERNEL MESSAGES", "diff_initcalls"),
                 "regions": ("KERNEL MESSAGES", "diff_regions"),
                 }


def do_diff(file1, file2, options):
    # output a diff of two files
    req_section = None
    if "-s" in options:
        req_section  = get_opt_with_arg('-s')

    if "-l" in options:
        sections = list(section_prefs.keys())
        sections.sort()
        print("Here are the sections you can use with 'diff':")
        for section in sections:
              print("  " + section)
        sys.exit(0)


    # outline:
    #  parse requested section
    #  validate requested section
    #  loop over sections

    # create a diff per section:
    # parse requested section name, if any
    if req_section and req_section not in section_prefs:
        error_out("Invalid section or data '%s' requested." % req_section)

    if req_section and not req_section == "all":
        req_sections = [req_section]
    else:
        req_sections = ["gbd", "kernel", "os", "mem", "disk", "mounts",
                        "processes", "cores", "config", "systemd", "kmsg",
                        "initcalls", "regions"]

    bd1 = boot_data_parser.parse_boot_data(None, file1)
    bd2 = boot_data_parser.parse_boot_data(None, file2)

    desc1 = get_descriptor(file1)
    desc2 = get_descriptor(file2)

    for section in req_sections:
        pref = section_prefs[section]
        sec_name = pref[0]
        diff_method = pref[1]
        title_extra = ""
        if diff_method == "text":
            output = diff_ext(bd1, bd2, desc1, desc2, sec_name, "diff -u")
        elif diff_method == "diff_mem":
            output = diff_mem(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_processes":
            output = diff_processes(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_modules":
            output = diff_modules(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_config":
            output = diff_config(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_systemd":
            output = diff_systemd(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_kmsg":
            output = diff_kmsg(bd1, bd2, desc1, desc2)
        elif diff_method == "diff_initcalls":
            output = diff_initcalls(bd1, bd2, desc1, desc2)
            title_extra = "data in "
        elif diff_method == "diff_regions":
            output = diff_regions(bd1, bd2, desc1, desc2)
            title_extra = "data in "
        else:
            wprint("FIXTHIS - diff_method '%s' for section '%s' is not implemented" % (diff_method, section))

        print("== diff for %ssection %s ==" % (title_extra, sec_name))
        print(output)
        print()

    sys.exit(0)

# find baseline and results files that match the indicated string
# string can contain a directory (ex: /tmp/bttw-dir/run-123456)
# if no directory specified, then just match the string.
# NOTE- string must be long enough to uniquely match one and only
# one baseline filename and one results filename.
def get_matching_files(file_match_str):
    baseline_path = None
    results_path = None

    scan_dir = os.path.dirname(file_match_str)
    if not scan_dir:
        scan_dir = "."

    match_expr = os.path.basename(file_match_str)

    for candidate in os.listdir(scan_dir):
        if match_expr in candidate:
            if "baseline" in candidate:
                if not baseline_path:
                    baseline_path = scan_dir + "/" + candidate
                else:
                    error_out("Multiple files match '%s" % file_match_str)
            if "results" in candidate:
                if not results_path:
                    results_path = scan_dir + "/" + candidate
                else:
                    error_out("Multiple files match '%s" % file_match_str)

    return baseline_path, results_path

def main():
    global debug
    global verbose
    global duration_threshold
    global max_count
    global dur_thresh_percent
    global have_threshold

    # allow error-free piping to other command line utilities (like 'head')
    signal(SIGPIPE, SIG_DFL)

    # parse command line arguments
    file1 = None
    file2 = None
    item_type = None
    # default threshold to 10ms
    duration_threshold = 10000
    max_count = 10
    file_match_str = ""
    cmd = ""

    if "-h" in sys.argv or "--help" in sys.argv:
        usage()
    if '-V' in sys.argv or '--version' in sys.argv:
        show_version()

    verbose = get_boolean_opt('-v')
    debug = get_boolean_opt('--debug')

    # flow debug setting into boot_data_parser (if needed)
    #if debug:
    #    boot_data_parser.set_debug(debug)

    if get_boolean_opt('list'):
        cmd = "list"

    if get_boolean_opt('show'):
        cmd = "show"

    if get_boolean_opt('diff'):
        cmd = "diff"

    if get_boolean_opt('compare'):
        cmd = "compare"

    if get_boolean_opt('top'):
        cmd = "top"

    if "-f" in sys.argv:
        file2 = get_opt_with_arg('-f')
        if not is_readable_file(file2):
            error_out("'%s' is not a readable file" % file2)

    allowed_item_types = ["meta", "initcall", "region", "systemd", "config"]
    if "-t" in sys.argv:
        item_type = get_opt_with_arg('-t')
        if item_type not in allowed_item_types:
            error_out("Invalid item type. Please use one of the following: %s" % allowed_item_types)

    if "-d" in sys.argv:
        dur_str = get_opt_with_arg('-d')
        try:
            duration_threshold = int(dur_str)
        except ValueError:
            error_out("Invalid duration. Please specify an integer")
        dur_thresh_percent = 0
        have_threshold = True

    if "-c" in sys.argv:
        count_str  = get_opt_with_arg('-c')
        try:
            max_count = int(count_str)
        except ValueError:
            error_out("Invalid count. Please specify an integer")

    if "-m" in sys.argv:
        file_match_str  = get_opt_with_arg('-m')

    if "-p" in sys.argv:
        dur_str = get_opt_with_arg('-p')
        try:
            dur_thresh_percent = int(dur_str)
        except ValueError:
            error_out("Invalid duration. Please specify an integer")
        duration_threshold = 0
        have_threshold = True


    if file_match_str:
        # look for 'baseline' and 'results' files matching this string:
        file1, file2 = get_matching_files(file_match_str)

    # done with general parsable args...
    # first non-arg should be the boot data file
    if not file1:
        try:
            file1 = sys.argv[1]
            sys.argv.remove(file1)
        except IndexError:
            if cmd != "list":
                error_out("Missing boot-data file argument (use -h for help)")

    # sanity check some args
    if file1 and not is_readable_file(file1):
        error_out("Missing or invalid boot-data file: %s" % file1)

    if not cmd:
        error_out("Missing command (use -h for help)")

    if cmd in ["compare", "diff"] and not file2:
        error_out("Missing second boot-data file argument\n  (use -f to specify, and -h for help)")

    options = sys.argv[1:]

    # done parsing command line
    if cmd == "list":
        do_list(file1, item_type)

    if cmd == "show":
        do_show(file1, options)

    if cmd == "top":
        do_top(file1, item_type, options)

    if cmd == "compare":
        do_compare(file1, file2, options)

    if cmd == "diff":
        do_diff(file1, file2, options)


    error_out("Unrecognized command '%s'" % cmd)

if __name__ == "__main__":
    main()
