#!/usr/bin/python3
# SPDX-License-Identifier: MIT
# vim: set ts=4 sw=4 et :
#
# boot-time-wizard.py
#   Run a series of measurements and tests, to try to optimize boot-time
#     for a platform
#
# Author: Tim Bird <tim.bird@sony.com>
#
# Copyright 2026 Sony Group Corporation
#
# todo:
# - test looping
#   - does kernel_id (run portion) increment correctly?
#   - does source, cmdline, config get restored correctly?
# - manage method.needs_kbuild
# - hide stderr from builds, if requested (default opt-in to build messages)
#   - or show if requested (default opt-out to build messages)
# - detect build failures
# - handle different optimization methods:
#   - remove udev entries
#   - remove SELinux rules
# - during test, check that system still behaves properly
#   - do a system sanity check
#   - allow specifying a validation function or program
# - try multiple methods
#   - undo each method before trying the next one
#   - allow stacking of methods
#     - do not undo each method before trying the next one
#   - select method(s) to use
#     - find element(s) to change (something over 10 ms)
#
# overall flow:
#  for a given item:
#    baseline: instrument, build, boot, measure, check functionality
#    test: alter, build, boot, measure, check functionality
#    recover: de-instrument, restore (build, boot, check)
#    analyze: compare results, make recommendations
#
# Notes:
# - use instrumentation to determine if a kernel feature is used or not,
#    and turn it off in kernel config, dt, command line, systemd, or in source
# - instrumentation can use /proc, /sys, ftrace, inserted printks
#   - printks can be programmatically inserted (maybe by AI?)
# - need to validate that nothing breaks with a comprehensive workload and
#   test cycle
# - examples:
#   - disable or remove all DT devices that are not loaded during a normal boot
# - lists of items to try: bluetooth, sound, video, serial console,
#   - wifi, disable polkit, disable ptrace, disable users,
#   - trim filesystems, trim code, remove unused dma items, remove drivers,
#   - remove unused crypto algorithms, remove unused syscalls
#   - remove unused device nodes, remove unused keymaps, disable printks
#   - remove kernel functions (directly, not via config)
# - need automated recovery in case of over-adjustment
#   - platform needs to support direct automated kinstall, or
#   - platform needs automatic reversion to recovery kernel
#     (e.g. support for boot-once)
# - may need mappings:
#   - code -> config
#   - instrumentation -> code location (e.g. printk -> config)
#   - procfs info -> driver/feature -> code -> config or DT node
#   - sysfs info -> driver/feature -> config or DT node
#

VERSION=(0,5,0)

import sys
import os
import re
import shutil
from signal import signal, SIGPIPE, SIG_DFL
from subprocess import getstatusoutput
import subprocess
import random
import time

debug = False
verbose = False

DEFAULT_GBD_SCRIPT_PATH = "/usr/local/bin"
ALTERNATE_GBD_SCRIPT_PATH = "/home/tbird/bin"
gbd_script_path = None

# use run_prefix to distinguish files in the artifact directory
run_prefix = "run-000000-"
# put this on test kernels to distinguish them
kernel_id = "999999"

def eprint(msg):
    sys.stderr.write("Error: " + msg + '\n')
    sys.stderr.flush()

def error_out(msg, rcode=-1):
    eprint(msg)
    sys.exit(rcode)

WARNING_SLEEP_SECS=5

def wprint(msg):
    sys.stderr.write("Warning: " + msg + '\n')
    sys.stderr.flush()
    time.sleep(WARNING_SLEEP_SECS)

def dprint(msg):
    global debug

    if debug:
        print("DEBUG: " + str(msg))

def vprint(msg):
    global verbose

    if verbose:
        print(msg)

# use 'TRB' in name so I can find and move it easily
def TRB_wait_for_input(msg):
    return(input("** %s: continue? " % msg))

def is_readable_file(filepath):
    real_path = os.path.realpath(filepath)
    if not os.path.isfile(real_path):
        return False
    return os.access(real_path, os.R_OK)


def is_executable_file(filepath):
    real_path = os.path.realpath(filepath)
    if not os.path.isfile(real_path):
        return False
    return os.access(real_path, os.X_OK)


# put a wrapper around subprocess execution
# if in verbose mode,
#   output to my stdout while the subprocess is running
#   and return the empty string as output
# else use getstatusoutput to capture (and hide) the subprocess output.
# returns (status, output)
def execute(cmd, verbose=False):
    if verbose:
        try:
            result = subprocess.run(cmd, shell=True)
            status = result.returncode
            output = ""
        except subprocess.CalledProcessError as cp:
            status = cp.returncode
            output = cp.output

        return (status, output)
    else:
        return getstatusoutput(cmd)

# parse kernel config into a dictionary
# returns a dictionary of (long) config names and their values
def parse_kernel_config(config_text):
    CONFIGS = {}
    for line in config_text.split('\n'):
        line = line.strip()
        # skip blank and comment lines
        if not line:
            continue
        if line.startswith("#") and not line.endswith(" is not set"):
            continue
        if line.startswith("CONFIG_"):
            name, value = line.split("=", 1)
            CONFIGS[name] = value
        elif line.endswith(" is not set"):
            # strip leading '# '
            name = line[2:].split(" ")[0]
            CONFIGS[name] = "n"
        else:
            eprint("weirdness in config file at line: '%s'" % line)
    return CONFIGS

# define a class for optimization methods
class opt_method_class():
    def __init__(selfm, name, description, opt_type="unknown"):
        selfm.name = name
        selfm.description = description
        selfm.opt_type = opt_type
        selfm.results_txt = "#"*70  + "\n" + \
            "=== Results report for optimization method '%s' ===\n" % name
        selfm.compare_list = ["time_to_init"]

        # artifact_prefix gets set later
        # set to something that will raise exception if used in string context
        selfm.artifact_prefix = 999
        selfm.needs_kbuild = False
        selfm.instrumentation_list = []

    def save_baseline(self, arg):
        raise NotImplementedError

    def restore_baseline(self, arg):
        raise NotImplementedError

    def instrument_target(selfm, target):
        # all instrumentation actions occur while we're in the kernel src dir
        target.change_to_src_dir()

        if selfm.instrumentation_list:
            # do two passes, patches and instr_type validation first
            for instr_tuple in selfm.instrumentation_list:
                instr_type = instr_tuple[0]
                instr_data = instr_tuple[1:]
                if instr_type == "patch":
                    dprint("Doing instrumentation: '%s'" % str(instr_tuple))
                    target.apply_patch(instr_data[0])
                    selfm.needs_kbuild = True
                elif instr_type in ["printk", "cmdline"]:
                    continue
                else:
                    error_out("Invalid instrumentation type '%s' for method '%s'" % (instr_type, selfm.name))

            # now do printks and cmdlines
            for instr_tuple in selfm.instrumentation_list:
                instr_type = instr_tuple[0]
                instr_data = instr_tuple[1:]
                if instr_type == "printk":
                    dprint("Doing instrumentation: '%s'" % str(instr_tuple))
                    # instr_data should be a 3-tuple here
                    target.add_printk(*instr_data)
                    selfm.needs_kbuild = True
                elif instr_type == "cmdline":
                    dprint("Doing instrumentation: '%s'" % str(instr_tuple))
                    target.add_cmdline(instr_data[0])
        else:
            print("No instrumentation added.")

        # wait for input (to investigate what happened)
        #TRB_wait_for_input("Check instrumentation, then press enter>")

        target.change_to_start_dir()

    def de_instrument_target(selfm, target):
        target.change_to_src_dir()
        target.restore_cmdline()
        target.restore_ksrc_files()
        target.unapply_patches()
        target.change_to_start_dir()

    def detect_optimization(selfm, arg):
        # should return (TRUE|FALSE, msg)
        return NotImplementedError

    def apply_optimization(selfm, arg, kernel_id=None):
        raise NotImplementedError

    def set_results(selfm, results_txt):
        selfm.results_txt += results_txt
        selfm.results_txt += "\n##########\n"

    def show_results(selfm):
        print(selfm.results_txt)

    def get_compare_list(selfm):
        # return method-specific items to compare in a report
        return selfm.compare_list

    def add_instrumentation(selfm, instr_tuple):
        # do some validation
        # printk is (type, region, position, location)
        instr_type = instr_tuple[0]
        if instr_type == "printk":
            position = instr_tuple[2]
            if position not in ["before", "after"]:
                error_out("Invalid position in instrumentation %s" % str(instr_tuple))

        # t is a tuple for either printk or patch instrumentation
        selfm.instrumentation_list.append(instr_tuple)
        if instr_type in ["printk", "patch"]:
            selfm.needs_kbuild = True

# the optimization method class for config items
class config_om_class(opt_method_class):
    def __init__(selfcm, name, description, config_name, config_value):
        super().__init__(name, description, "kernel_config")
        selfcm.config_name = config_name
        selfcm.config_value = config_value
        selfcm.needs_kbuild = True

    def save_baseline(selfcm, target):
        target.save_build_config()
        return

    def restore_baseline(selfcm, target):
        target.change_to_src_dir()

        target.restore_build_config()

        print(" - Rebuilding kernel...")
        status, output = target.ttc("kbuild", verbose)

        print(" - Installing kernel...")
        status, output = target.ttc("kinstall", verbose)

        # reset working dir to where we started
        target.change_to_start_dir()

    def detect_optimization(selfcm, target):
        # report whether this optimization is already applied
        # check config, return a string
        configs = target.get_target_configs()
        config_name = selfcm.config_name
        config_value = selfcm.config_value

        if config_name not in configs:
            return (False, "config %s not found" % config_name)

        if configs[config_name] == config_value:
            return (True, "config %s has the value '%s'" % config_name, config_value)
        else:
            return (False, "config %s: current value '%s' != optimized value %s" % (config_name, configs[config_name], config_value))

    def apply_optimization(selfcm, target, kernel_id):
        target.change_to_src_dir()

        # check if config is different from requested value
        configs = target.get_target_configs()

        old_value = configs.get(selfcm.config_name, "missing")
        new_value = selfcm.config_value

        old_build_value = target.get_build_config(selfcm.config_name)

        dprint("config: old_build_value=%s, old_value=%s, new_value=%s" % (old_build_value, old_value, new_value))
        # compare config in source with config
        if old_value == new_value:
            wprint("in apply_optimization, old config value matches requested config value")
            wprint(" old_value=%s, new_value=%s, old_build_value=%s" % (old_value, new_value, old_build_value))

        # set config to new value
        print(" - Applying optimization: changing config value %s: %s -> %s" % (selfcm.config_name, old_build_value, new_value))
        target.set_build_config(selfcm.config_name, new_value)

        # wait for input (to investigate what happened)
        #TRB_wait_for_input("Check optimzation application")

        selfcm.saved_value = old_build_value

        # set kernel id, then build
        status = target.rebuild_and_install(kernel_id)

        return status

    def undo_optimization(selfcm, target):
        target.change_to_src_dir()

        # set config to saved value
        #target.set_build_config(selfcm.config_name, selfcm.saved_value)
        #print(" - Undoing optimization: changing config value %s=%s", selfcm.config_name, selfcm.saved_value)

        # revert to saved build config
        target.restore_build_config()

        # clear kernel id
        target.clear_localversion()

        # reset working dir to where we started
        target.change_to_start_dir()
        return


# the optimization method class for kernel command line options
class cmdline_om_class(opt_method_class):
    def __init__(selflm, name, description, option_str):
        super().__init__(name, description, "kernel_cmdline")
        selflm.option_str = option_str
        if "=" in option_str:
            selflm.option_name, selflm.option_value = option_str.split("=", 1)


    def save_baseline(selflm, target):
        # save the current (configured) target cmdline
        status, cur_cmdline = target.ttc("get_cmdline")
        saved_cmdline_path = target.artifact_prefix + "saved_cmdline.txt"
        with open(saved_cmdline_path, "w") as fd:
                  fd.write(cur_cmdline)
        return

    def restore_baseline(selflm, target):
        saved_cmdline_path = target.artifact_prefix + "saved_cmdline.txt"
        cmdline = open(saved_cmdline_path, "r").read().rstrip()
        status, output = target.ttc("set_cmdline -r " + cmdline)

    def detect_optimization(selflm, target):
        # report whether this optimization is already applied
        # check config, return a string
        status, cmdline = target.ttc("get_cmdline -s")

        if selflm.option_str in cmdline:
            return (True, "cmdline option '%s' is already in current command line" % selflm.option_str)

        return (False, "Did not find '%s' in current command line" % selflm.option_str)

    def apply_optimization(selflm, target, kernel_id):
        print(" - Applying optimization: adding '%s' to command line" % selflm.option_str)

        status, cmdline = target.ttc("get_cmdline")
        if status != 0:
             eprint("Could not get current configured command line")

        selflm.saved_cmdline = cmdline

        # FIXTHIS - for now, assume optimization option can be appended at the end of cmdline
        status, output = target.ttc("set_cmdline " + selflm.option_str)
        return status

    def undo_optimization(selflm, target):
        status, cmdline = target.ttc("set_cmdline -r " + selflm.saved_cmdline)
        if status != 0:
             eprint("Could not set current configured command line")
        return

# the optimization method class for trimming device tree items
class dt_om_class(opt_method_class):
    def __init__(selfdtm, name, description, dt_name):
        super().__init__(name, description, "dt_disable")
        selfdtm.dt_name = dt_name
        selfdtm.needs_kbuild = True

    def save_baseline(selfdtm, target):
        # save the current (configured) target cmdline
        status, cur_cmdline = target.ttc("get_cmdline")
        saved_cmdline_path = target.artifact_prefix + "dt_saved_cmdline.txt"
        with open(saved_cmdline_path, "w") as fd:
                  fd.write(cur_cmdline)
        return

    def restore_baseline(selfdtm, target):
        saved_cmdline_path = target.artifact_prefix + "dt_saved_cmdline.txt"
        cmdline = open(saved_cmdline_path, "r").read().rstrip()
        status, output = target.ttc("set_cmdline -r " + cmdline)

    def detect_optimization(selfdtm, target):
        # report whether this optimization is already applied
        # check config, return a string
        dts = target.get_dts_status()
        dprint(f"in detect_optimization: {dts=}")

        dt_name = selfdtm.dt_name

        # make sure dt_om_class::detect_optimization works
        if dt_name not in dts:
            return (False, "device-tree node '%s' not found" % dt_name)
        status = dts[dt_name]

        if status == "disabled":
            return (True, "device-tree node '%s' is already disabled" % dt_name)
        else:
            return (False, "device-tree node '%s': current status is: '%s'" % (dt_name, status))

    def apply_optimization(selfdtm, target, kernel_id):
        # check if config is different from requested value
        dts = target.get_dts_status()
        dt_name = selfdtm.dt_name

        # disable the dt
        dt_disable_str="fdt.disable=%s" % dt_name
        print(" - Applying optimization: changing dt %s status to 'disabled'" % dt_name)
        status, cmdline = target.ttc("get_cmdline")
        if status != 0:
             eprint("Could not get current configured command line")

        selfdtm.saved_cmdline = cmdline

        # optimization option can be appended at the end of cmdline
        status, output = target.ttc("set_cmdline " + dt_disable_str)
        return status

    def undo_optimization(selfdtm, target):
        status, cmdline = target.ttc("set_cmdline -r " + selfdtm.saved_cmdline)
        if status != 0:
             eprint("Could not set current configured command line")
        return

# the optimization method class for kernel command line options
class systemd_om_class(opt_method_class):
    def __init__(selfsdm, name, description, option_str):
        super().__init__(name, description, "systemd")
        selfsdm.unit_name = option_str

    def save_baseline(selfsdm, target):
        # save the current (configured) target cmdline
        cmd = "SYSTEMD_COLORS=0 systemctl list-unit-files -l --no-pager"
        status, cur_unit_status = target.run(cmd)
        saved_systemd_path = target.artifact_prefix + "saved_systemd.txt"
        with open(saved_systemd_path, "w") as fd:
                  fd.write(cur_unit_status)
        return

    def restore_baseline(selfsdm, target):
        # restore all units to original status
        saved_systemd_path = target.artifact_prefix + "saved_systemd.txt"
        unit_status = open(saved_systemd_path, "r").read().rstrip()
        # FIXTHIS - add code to restore systemd status based on saved unit status list
        wprint("Restore_baseline() not finished for systemd_om_class")
        #TRB_wait_for_input("** Press enter to continue> ")

    def detect_optimization(selfsdm, target):
        # report whether this optimization is already applied
        # check state, return a tuple
        cmd = '"systemctl is-enabled %s"' % selfsdm.unit_name
        status, output = target.run(cmd)
        unit_state = output.strip()
        if unit_state not in ["enabled", "disabled", "not-found"]:
            wprint("problem reading UnitFileState: %s" % output)
            unit_state = "unknown"

        if unit_state == "disabled":
            return (True, "unit '%s' is already disabled" % selfsdm.unit_name)
        elif unit_state == "enabled":
            return (False, "unit '%s' is enabled" % selfsdm.unit_name)
        elif unit_state == "not-found":
            return (False, "Did not find '%s' on target" % selfsdm.unit_name)
        else:
            return (False, "Unexpected error with systemctl")

    def apply_optimization(selfsdm, target, kernel_id):
        print(" - Applying optimization: disabling '%s'" % selfsdm.unit_name)

        cmd = "systemctl disable " +  selfsdm.unit_name
        status, output = target.run(cmd)
        if status != 0:
             eprint("Could not disable %s" % selfsdm.unit_name)
        return status

    def undo_optimization(selfsdm, target):
        status, output = target.run("systemctl enable " + selfsdm.unit_name)
        if status != 0:
            eprint("Could not enable %s: output='%s'" % (selfsdm.unit_name, output))
        return


class target_class():
    def __init__(selft, name):
        # save start dir for restoration later
        selft.start_dir = os.getcwd();

        # sets up target instance
        # raises ValueError on invalid target name
        selft.name = name
        # make sure target is recognized by ttc
        status, output = selft.ttc("info")
        if status != 0:
            raise ValueError

        # set some variables we may need later
        selft.KERNEL_SRC = selft.get_ttc_var("KERNEL_SRC", ".")
        if not os.path.isfile(selft.KERNEL_SRC + "/MAINTAINERS"):
            wprint("Missing MAINTAINERS file in KERNEL_SRC dir: %s - check configuration" % selft.KERNEL_SRC)
            dprint("current dir=%s" % os.getcwd())

        # make KERNEL_SRC path absolute
        selft.KERNEL_SRC = os.path.abspath(selft.KERNEL_SRC)

        selft.KBUILD_OUTPUT = selft.get_ttc_var("KBUILD_OUTPUT", selft.KERNEL_SRC)

        # make this path absolute
        selft.change_to_src_dir()
        selft.KBUILD_OUTPUT = os.path.abspath(selft.KBUILD_OUTPUT)
        selft.change_to_start_dir()

        selft.CONFIGS = {}   # fill the CONFIGS dictionary in, as needed
        selft.config_saved = False

        selft.artifact_prefix = 999
        selft.saved_ksrc_files = []
        selft.applied_ksrc_patches = []
        selft.patch_dir = ""

        selft.orig_cmdline = ""
        status, cmdline = selft.ttc("get_cmdline")
        if status != 0:
             eprint("Could not get (original) current configured command line")
        selft.orig_cmdline = cmdline

    # return the output from 'ttc target cmd'
    def ttc(selft, cmd, echo=False):
        cmdline = "ttc %s %s" % (selft.name, cmd)
        status, output = execute(cmdline, echo)
        if echo:
            print(output)
        dprint("cmdline='%s'" % cmdline)
        dprint("output='%s'" % output)
        return (status, output)

    def get_ttc_var(selft, var, default):
        status, output = execute("ttc %s info -n %s" % (selft.name, var))
        if status == 0:
            return output.strip()
        else:
            return default

    def run(selft, cmd, echo=False):
        return selft.ttc("run " + cmd, echo)

    def put(selft, src_path, dest_path):
        return selft.ttc("cp %s target:%s" % (src_path, dest_path))

    def get(selft, src_path, dest_path):
        return selft.ttc("cp target:%s %s" % (src_path, dest_path))

    def reboot_and_wait(selft, echo=True):
        status, output = selft.ttc("reboot", echo)
        status2, output2 = selft.ttc("wait_for -t 30 ttc run true", echo)
        return status2, output + output2

    def get_target_config(selft):
        # returns the kernel configuration from a target as a string

        # look on the target in a variety of locations for the kernel config
        # if found, return the kernel config
        # if not, return the empty string
        status, output = selft.run("zcat /proc/config.gz")
        if status == 0:
            return output

        status, output = selft.run("uname -r")
        if status == 0:
            release = output.strip()

        # if there's a config.ko module, try installing it
        config_ko_path = "/lib/modules/%s/kernel/kernel/configs.ko" % release
        status, output = selft.run("test -f %s" % config_ko_path)
        if status == 0:
            selft.run("insmod %s" % config_ko_path)
            status, output = selft.run("zcat /proc/config.gz")
            selft.run("rmmod configs")
            if status == 0:
                return output

        # if there's a config.ko.xz module, try installing it
        config_koxz_path = "/lib/modules/%s/kernel/kernel/configs.ko.xz" % release
        status, output = selft.run("test -f %s" % config_koxz_path)
        if status == 0:
            selft.run("insmod %s" % config_koxz_path)
            status, output = selft.run("zcat /proc/config.gz")
            selft.run("rmmod configs")
            if status == 0:
                return output

        # if there's a build .config file, return that
        build_config_path = "/lib/modules/%s/build/.config" % release
        status, output = selft.run("test -f %s" % build_config_path)
        if status == 0:
            status, output = selft.run("cat %s" % build_config_path)
            if status == 0:
                return output

        # check /boot directory
        boot_config_path = "/boot/config-%s" % release
        status, output = selft.run("test -f %s" % boot_config_path)
        if status == 0:
            status, output = selft.run("cat %s" % boot_config_path)
            if status == 0:
                return output

        boot_config_path = "/boot/config"
        status, output = selft.run("test -f %s" % boot_config_path)
        if status == 0:
            status, output = selft.run("cat %s" % boot_config_path)
            if status == 0:
                return output

        return ""

    def get_target_configs(selft):
        # returns the kernel configuration from a target as a dictionary
        # config names are long, including CONFIG_ prefix
        # (e.g. 'CONFIG_CMDLINE')
        if selft.CONFIGS:
            return selft.CONFIGS

        config_text = selft.get_target_config()
        if config_text:
            CONFIGS = parse_kernel_config(config_text)
            selft.CONFIGS = CONFIGS

        return selft.CONFIGS

    def change_to_src_dir(selft):
        os.chdir(selft.KERNEL_SRC)

    def change_to_start_dir(selft):
        os.chdir(selft.start_dir)

    def get_build_config(selft, config_name):
        # returns the value of a single config option in the current
        # build config

        # read build configs file ($KBUILD_OUTPUT/.config)
        config_path = selft.KBUILD_OUTPUT + "/.config"
        value = "undefined"
        with open(config_path, "r") as fd:
            for line in fd.readlines():
                line = line.strip()
                if not line:
                    continue
                if line.startswith("%s=" % config_name):
                    value = line.split("=")[1].strip()
                    break
                if line.startswith("# %s=" % config_name) and \
                    line.endswith(" is not set"):
                    value = "n"
                    break

        return value

    def save_build_config(selft):
        if not selft.config_saved:
            # put original build configs into artifact dir
            config_path = selft.KBUILD_OUTPUT + "/.config"
            save_path = selft.artifact_prefix + "saved-config"
            dprint("Saving build config: from %s to %s" % (config_path, save_path))
            shutil.copy(config_path, save_path)
            selft.config_saved = True

    def restore_build_config(selft):
        if not selft.config_saved:
            eprint("Error restoring build config - original config was not saved!")
            return

        # copy original build configs back into build dir
        save_path = selft.artifact_prefix + "saved-config"
        config_path = selft.KBUILD_OUTPUT + "/.config"
        dprint("Restoring build config: from %s to %s" % (save_path, config_path))
        shutil.copy(save_path, config_path)

    def set_build_config(selft, config_name, config_value):
        global verbose

        cmd = 'set_config "%s=%s"' % (config_name, config_value)
        # FIXTHIS - need to test set_build_config with quoted string values

        return selft.ttc(cmd, verbose)

    def set_localversion(selft, lver_str):
        lv_path = selft.KERNEL_SRC + "/localversion"
        lv_file = open(lv_path, "w")
        lv_file.write("-" + lver_str + "\n")
        lv_file.close()
        selft.kernel_id = lver_str

    def clear_localversion(selft):
        # we should be in the KERNEL_SRC dir by now
        lv_path = selft.KERNEL_SRC + "/localversion"
        try:
            os.unlink(lv_path)
        except:
            pass

    def check_localversion(selft, lver_str = None):
        if not lver_str:
            lver_str = selft.kernel_id
        rcode, output = selft.run("uname -r")
        if lver_str in output:
            return True
        else:
            return False

    def rebuild_and_install(selft, localversion=""):
        # NOTE: if you pass a localversion, any preset localversion
        # will be cleared when this function returns.
        selft.change_to_src_dir()

        if localversion:
            selft.set_localversion(localversion)

        status, output = selft.ttc("kbuild", verbose)
        if status != 0:
            eprint("kbuild failure: output='%s'" % output)
            return status

        status, output = selft.ttc("kinstall", verbose)
        if status != 0:
            eprint("kinstall failure: output='%s'" % output)
            return status

        if localversion:
            selft.clear_localversion()

        selft.change_to_start_dir()
        return 0

    def save_ksrc_file(selft, filepath):
        orig_path = selft.KERNEL_SRC + "/" + filepath
        save_path = selft.KERNEL_SRC + "/" + filepath + ".btw-orig"

        # check if we've already saved it
        if filepath in selft.saved_ksrc_files:
            # have a duplicate save request for this file
            if os.path.exists(save_path):
                # if backup already exists, it's ok, we're done
                #vprint("Note: File '%s' is already on saved file list" % filepath)
                return
            else:
                # if not, something's gone wrong
                print("Error: backup file handling error for '%s'" % filepath)
                print("file was already on saved_src_files list, but backup is not present")
                print("Manually validate the file and restart.")
                error_out("Aborting now to avoid damage to src tree")

        if not os.path.exists(save_path):
            # if save is not there, save it now
            shutil.copy(orig_path, save_path)
            selft.saved_ksrc_files.append(filepath)

        if not filepath in selft.saved_ksrc_files:
            print("Error: backup file handling error for '%s'" % filepath)
            print("File should have been on saved_src_files list, but was not")
            print("Manually restore file from '%s', remove backup, and restart." % save_path)
            error_out("Aborting now to avoid damage to src tree")

    def restore_ksrc_files(selft):
        for filepath in selft.saved_ksrc_files:
            orig_path = selft.KERNEL_SRC + "/" + filepath
            saved_path = selft.KERNEL_SRC + "/" + filepath + ".btw-orig"
            if not os.path.exists(saved_path):
                print("Error: backup file handling error for '%s' in restore_ksrc_files()" % filepath)
                print("backup file '%s' (on saved_src_files list) is not present in filesystem" % saved_path)
                continue

            shutil.copy(saved_path, orig_path)
            os.unlink(saved_path)
            # after restoring this filepath, remove from list
            selft.saved_ksrc_files.remove(filepath)

        # if there are files left over, something went wrong
        if selft.saved_ksrc_files:
            # show a message and some diagnostic info
            print("Error: backup file handling error in restore_ksrc_files()")
            print("The following files on the restore list were not restored!!")
            print("Manually restore files and restart.")
            print("Search for added printks by grepping 'BTTW'\n")
            print("Affected files:")
            for filepath in selft.saved_ksrc_files:
                orig_path = selft.KERNEL_SRC + filepath
                print("  " + orig_path)
            error_out("Aborting now to avoid damage to src tree")

    # location is <file>:<line_expr>
    # position="before" or "after"
    def add_printk(selft, region, position, location):
        printk_str = 'printk(KERN_INFO "BTTW: %s %s\\n");\n' % (position, region)
        if ":" in location:
            filepath, expr = location.split(":", 1)
        else:
            error_out("Unsupported location '%s' in add_printk" % location)

        # check that file exists
        full_path = selft.KERNEL_SRC + "/" + filepath
        if not is_readable_file(filepath):
            print("Error: could not file file '%s'" % filepath)
            error_out("Invalid file in location '%s' in add_printk" % location)

        # save a backup of the file
        selft.save_ksrc_file(filepath)

        # load file
        lines = open(full_path, "r").readlines()
        new_lines = []

        # only add at first location
        added = False
        for line in lines:
            if (not added) and re.search(expr, line):
                # got a match, insert the line
                left_whitespace_len = len(line) - len(line.lstrip())
                prefix = line[:left_whitespace_len]
                new_line = prefix + printk_str
                if position == "before":
                    new_lines.append(new_line)
                    new_lines.append(line)
                else:
                    new_lines.append(line)
                    new_lines.append(new_line)
                added = True
            else:
                new_lines.append(line)

        content = "".join(new_lines)

        with open(full_path, "w") as outfile:
            outfile.write(content)

        if not added:
            wprint("Could not add printk %s %s" % (position, location))


    def unapply_patches(selft):
        # get a new list, since we'll modify the old one
        patch_list = selft.applied_ksrc_patches.copy()
        # back them out in reverse order
        patch_list.reverse()
        for patch_name in patch_list:
            patch_path = selft.patch_dir + "/" + patch_name
            cmd ="git apply -R %s" % patch_path
            status, output = execute(cmd)
            if status != 0:
                print("Error: Could not remove patch '%s'" % patch_name)
                print("output='%s'" % output)
            else:
                selft.applied_ksrc_patches.remove(patch_name)

        if selft.applied_ksrc_patches:
            print("The following patches were not removed!!\n")
            print("Outstanding patches:")
            for patch_name in selft.applied_ksrc_patches:
                print("  "+patch_name)
            print("\nManually unapply patches (git apply -R), or reset tree.")
            print("Try: git reset --hard <good-top-commit>'\n")
            error_out("Aborting now to allow manual restoration of src tree")

    def apply_patch(selft, patch_name):
        # note that this doesn't create commits, which is harder to back out
        # alternate would be to use git am, but then backing out requires
        # a git reset, with a ORIG_HEAD that we saved
        patch_path = selft.patch_dir + "/" + patch_name
        cmd ="git apply %s" % patch_path
        status, output = execute(cmd)
        if status != 0:
            print("Error: Could not apply patch '%s'" % patch_name)
            print("output='%s'" % output)
            print("Instrumentation for test cannot be completed")
            print("Backing out of applied patches now...")
            if selft.applied_ksrc_patches:
                selft.unapply_patches()
            error_out("Aborting now to avoid damage to the src tree")
        else:
            selft.applied_ksrc_patches.append(patch_name)

    def add_cmdline(selft, arg):
        # assume cmdline arg can be appended at the end
        status = 0
        if selft.orig_cmdline:
            if arg not in selft.orig_cmdline:
                status, output = selft.ttc("set_cmdline " + arg)
        else:
            wprint("orig_cmdline not set!")
        return status

    def restore_cmdline(selft):
        status = 0
        if selft.orig_cmdline:
            status, output = selft.ttc("set_cmdline -r " + selft.orig_cmdline)
        else:
            wprint("orig_cmdline not set!")
        return status

    def get_dts_status(selft):
        # return a dictionary of dts with key=name, value=status
        dt_status_script = '"for sp in /proc/device-tree/aliases/* ; do s=\\$(basename \\$sp) ; dtp=\\$(cat \\$sp | tr -d \'\\0\') ; p=/proc/device-tree\\${dtp} ; st=\\${p}/status ; if [ -e \\$st ] ; then status=\\$(cat \\$st | tr -d \'\\0\') ; echo \\$s,\\$status ; fi ; done"'
        status, output = selft.run(dt_status_script)
        lines = output.split("\n")
        dprint(f"\nin get_target_dts_status: result from dt_status_script {lines=}")

        # parse output
        dts = {}
        for line in lines:
            if "," in line:
                dt, status = line.strip().split(",",1)
                dts[dt] = status

        return dts


def usage():
    print("""Usage: boot-time-wizard.py <options>

Run one or more optimization methods on a specified target, and
see how it affects the boot-time for the target.  Produce a report
showing the effect of each method and the cumulative effect of
all applied methods.

Options:
 -h, --help    Show this usage help

 -m <method>   Test specified optimization method

 -l            List optimization methods

 -t <target>   Specify the target to run tests on

 -d <dir>      Use <dir> for artifacts and test results
               (default is the './btw-artifacts')

 -k <kdir>     Use <kdir> as the kernel source directory.
               A kernel dir is required by some optimization methods,
               usually to allow instrumenting and rebuilding the kernel.
               If not specified, The program will detect if the current
               directory or 'linux' is a kernel source dir, and use that.
               If a kernel source dir cannot be found, optimizations
               that require it will be skipped.
               This overrides the kernel src directory provided by the
               target (in the ttc configuration).

 -v            Show verbose output.  When used with -l and -t, shows
               the status of each optimization method on the given target.

 -V, --version Show program version and exit.

Test options:
 --debug       Show debug information
 -r <run_id>   Generate a report from boot-data files from the indicated
               run_id.  Other parameters, such as -m, -t and -k must be
               the same as the original run.  The program must be run from
               the same directory as it was originally. This is primarily
               used to test the report generator, on a single method.
""")
    sys.exit(0)

# add printk instrumentation before and after a function call.
# The first function call in the file will be instrumented.
def add_function_instr(m, file, function):
    # function name must have only whitespace in front (to avoid
    # catching declarations), and have a '(' at the end
    # (to avoid partial function name matches)
    location = file + ":" + "^\\W+"+function + "\\("
    # use called function name as the region name
    m.add_instrumentation(("printk", function, "before", location))
    m.add_instrumentation(("printk", function, "after", location))

# returns a list of method instances
def init_methods(kernel_dir):
    # add methods
    methods = {}

    cur_dir = os.getcwd()

    # initialize optimization methods that require modifying or
    # reconfiguring the kernel
    if kernel_dir:
        m = config_om_class("disable-bluetooth-config", "Disable bluetooth by compiling kernel without it.", "CONFIG_BT", "N")
        m.compare_list = ["CONFIG_BT", "bt_init", "bluetooth.service"]
        m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
        methods[m.name] = m

        m = config_om_class("disable-sound-config", "Disable sound by compiling kernel without it.", "CONFIG_SOUND", "N")
        m.compare_list = ["CONFIG_SOUND", "alsa_pcm_init", "alsa_sound_init", "alsa_timer_init", "init_soundcore", "systemd-modules-load.service"]
        m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
        methods[m.name] = m

        m = config_om_class("disable-graphics-config", "Disable graphics by compiling kernel without it.", "CONFIG_DRM", "N")
        m.compare_list = ["CONFIG_DRM"]
        m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
        methods[m.name] = m

        m = config_om_class("disable-usb-config", "Disable USB by compiling kernel without it.", "CONFIG_USB", "N")
        m.compare_list = ["CONFIG_USB"]
        m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
        methods[m.name] = m

    m = cmdline_om_class("low-mem-500M-cmdline", "Reduce memory configure (to 500M) using cmdline option", "mem=500M")
    m.compare_list = ["MEM_TOTAL", "MEM_USED", "mm"]
    # FIXTHIS - these instrumentations should be generally applied
    m.add_instrumentation(("patch","early-times.patch"))
    m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
    methods[m.name] = m

    m = cmdline_om_class("low-mem-1G-cmdline", "Reduce memory configure (to 1G) using cmdline option", "mem=1G")
    m.compare_list = ["MEM_TOTAL", "MEM_USED", "mm"]
    m.add_instrumentation(("patch","early-times.patch"))

    # add some printk instrumentation
    add_function_instr(m, "init/main.c", "mm_core_init_early")
    add_function_instr(m, "init/main.c", "early_numa_node_init")
    add_function_instr(m, "init/main.c", "mm_core_init")
    add_function_instr(m, "init/main.c", "anon_vma_init")

    m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
    methods[m.name] = m

    m = dt_om_class("disable-bluetooth-dt", "Disable bluetooth device-tree node.", "bluetooth")

    # add patches first, then printks, then cmdlines
    m.add_instrumentation(("patch","cmdline-disable-dt1.patch"))
    m.add_instrumentation(("patch","cmdline-disable-dt2.patch"))
    m.add_instrumentation(("patch","cmdline-disable-dt3.patch"))

    #m.add_instrumentation(("printk","test_region", "before","init/main.c:kfence_init"))
    #m.add_instrumentation(("printk","test_region", "after","init/main.c:profile_init"))

    m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
    methods[m.name] = m

    # define a few systemd service disable methods
    m = systemd_om_class("disable-modem-manager-systemd", "Disable ModemManager.service.", "ModemManager.service")
    m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
    methods[m.name] = m

    m = systemd_om_class("disable-avahi-daemon-systemd", "Disable avahi-daemon.service.", "avahi-daemon.service")
    m.add_instrumentation(("cmdline","quiet log_buf_len=2M initcall_debug"))
    methods[m.name] = m

    dprint("== Methods ==")
    dprint(methods)


    # candidate methods:
    #   optimize udev (remove unused udev rules)
    #   optimize filesystems (eliminate unused filesystems)
    #   optimize kernel size
    #   use 'quiet'
    #   use deferred initcalls
    #   use deferred memory init
    #   disable printing
    #   optimize device tree (remove unused dt nodes)
    #   optimize security init (remove unused selinux rules)
    #   use async probing
    #   use async module loading

    return methods

# target can resolve to False, in which case showing
# optimization status is not available
def list_methods(methods, target):
    global verbose

    print("Available optimization methods:")
    for m in methods.values():
        print("  " + m.name, end="")
        if verbose and target:
            # show the status of optimization methods for the indicated target
            has_method, msg = m.detect_optimization(target)
            if has_method:
                print(", already present\n     (%s)" % msg)
            else:
                print(", not applied\n     (%s)" % msg)
        else:
            print()

    if not (verbose and target):
        print("\nNote: use -v and specify a target to see current status")

def try_one_method(method, target, artifact_prefix):
    global kernel_id
    global gbd_script_path

    print("##################################################")
    print("== Trying optimization method: %s" % method.name)

    # save off materials we might change
    method.save_baseline(target)

    print("== Preparing target: %s" % target.name)
    vprint(" - Installing grab-boot-data.sh...")
    # find suitable destination directory
    #  see if /usr/local/bin exists on target
    dest_dir = "/usr/local/bin"
    rcode, output = target.run("ls " + dest_dir)
    if "No such" in output:
        dest_dir = "/usr/bin"
        rcode, output = target.run("ls " + dest_dir)
        if "No such" in output:
            dest_dir = "/bin"

    # FIXTHIS - should record dest_dir for later cleanup
    # this may overwrite an existing grab-boot-data.sh script
    dprint(f"in try_one_method: {gbd_script_path=}, {dest_dir=}")
    status, output = target.put(gbd_script_path, dest_dir)
    # FIXTHIS - check status here??

    vprint(" - Gathering baseline boot data...")
    target.run("chmod a+x %s/grab-boot-data.sh" % dest_dir)

    print("== Measuring baseline for target: %s" % target.name)
    # measure metric we are trying to optimize
    # measure full boot time
    # get a baseline measurement
    vprint(" - Rebooting %s..." % target.name)
    status, output = target.reboot_and_wait()
    if status != 0:
        error_out("Problem rebooting %s" % target.name)

    status, output = target.run("/usr/local/bin/grab-boot-data.sh -l timslab -m %s -d /tmp -x" % (target.name))
    status, output = target.run("ls -t /tmp/boot-data* | tail -n 1")
    baseline_results_path=output.strip()
    baseline_file = "baseline-" + os.path.basename(baseline_results_path)
    dprint("boot-data baseline file for this run on the target is: %s" % baseline_results_path)

    # download and save boot data file
    dprint("#######################################################")
    vprint("== Retrieving baseline boot data from %s..." % baseline_results_path)
    local_baseline_path = artifact_prefix + baseline_file
    target.get(baseline_results_path, local_baseline_path)

    # apply method
    #  - determine new value for option
    #  - build, reboot, alter commands/parameters, etc.
    dprint("#######################################################")
    vprint("== Applying optimization %s" % method.name)
    method.apply_optimization(target, kernel_id)

    # boot machine
    dprint("#######################################################")
    vprint("== Rebooting machine (with test kernel)")
    status, output = target.reboot_and_wait()
    vprint(output)

    # measure metric we are trying to optimize
    # measure full boot time
    dprint("#######################################################")
    vprint("== Measuring with optimization")
    vprint(" - Gathering test results boot data...")
    status, output = target.run("/usr/local/bin/grab-boot-data.sh -l timslab -m %s -d /tmp -x" % (target.name))
    # download and save boot data file
    status, output = target.run("ls -t /tmp/boot-data* | tail -n 1")
    results_path=output.strip()
    dprint("boot-data file for this run on the target is: %s" % results_path)
    results_file="results-"+ os.path.basename(results_path)

    # download and save boot data file
    vprint(" - Retrieving test results boot data from %s..." % results_file)
    local_results_path = artifact_prefix + results_file
    target.get(results_path, local_results_path)

    dprint("#######################################################")
    vprint("== Comparing baseline with optimization results")

    # generate report
    report_data = gen_report_data(method, local_baseline_path, local_results_path)

    method.set_results(report_data)

    #TRB_wait_for_input("Check running kernel and dmesg for printks")

    # in try_one... we're not accumulating options
    # reset optimization status
    method.undo_optimization(target)

    # restore any materials we changed
    method.restore_baseline(target)

    print("== Done with method %s" % method.name)
    return output

def tune_boot_time(methods, target, artifact_prefix):
    global kernel_id

    rnd_str = artifact_prefix[-7:-1]

    print("Start of boot-time testing:")
    print("== Instrumenting target: %s, for method %s" % (target.name, method.name))
    method.instrument_target(target)

    # FIXTHIS - select methods intelligently, instead of just running through list, in tune_boot_time()

    # run through all listed methods
    mlist = list(methods.keys())

    for method in mlist:
        # advance run_count on each method tested
        rnd_str, run_count = kernel_id.split("-", 1)
        run_count = int(run_count) + 1
        kernel_id = "%s-%d" % (rnd_str, run_count)

        # try it
        try_one_method(method, target, artifact_prefix)

        # FIXTHIS - decide if optimization was worth it
        # check results

    print("== De-Instrumenting target")
    method.de_instrument_target(target)

    # build to get back to baseline kernel
    # rebuild kernel
    vprint(" - Rebuilding and installing kernel...")
    target.clear_localversion()
    status = target.rebuild_and_install()

    # reboot one last time to return to baseline kernel and settings
    target.ttc("reboot")

    print("Final tuning recommendations:...")

def report_header(run_id, tname, saved_args):
    global VERSION

    arg_str = " ".join(saved_args)

    from datetime import datetime

    now = datetime.now()
    time_str = now.strftime("%Y-%02m-%02d_%02H:%02M:%02S")
    header = """Boot-Time Wizard Report
==========================================
DATE_AND_TIME="%s"
RUN_ID="%s"
TARGET_NAME="%s"
BTTW_ARGS="%s"
BTTW_VERSION="%s.%s.%s"
==========================================
""" % (time_str, run_id, tname, arg_str, VERSION[0], VERSION[1], VERSION[2])

    return header

def log_to_report(artifact_prefix, msg, append=True):
    report_path = artifact_prefix + "report.txt"
    if append:
        mode = "a"
    else:
        mode = "w"

    with open(report_path, mode) as report_file:
        report_file.write(msg)

def get_opt_with_arg(arg):
    try:
        arg_pos = sys.argv.index(arg)
        var = sys.argv[arg_pos + 1]
        del sys.argv[arg_pos + 1]
        del sys.argv[arg_pos]
    except IndexError:
        error_out("Missing argument to '%s'. Use -h for help" % arg)

    return var

def get_boolean_opt(arg):
    if arg in sys.argv:
        sys.argv.remove(arg)
        return True
    else:
        return False

# set global gbd_script_path, where grab-boot-data.sh can
# be found, to use on the target
def find_gbd_script_path(script_dir):
    global gbd_script_path

    # try some different alternatives
    script_path = script_dir + "/grab-boot-data.sh"
    if is_executable_file(script_path):
        gbd_script_path = script_path
        return

    script_path = DEFAULT_GBD_SCRIPT_PATH + "/grab-boot-data.sh"
    if is_executable_file(script_path):
        gbd_script_path = script_path
        return

    script_path = ALTERNATE_GBD_SCRIPT_PATH + "/grab-boot-data.sh"
    if is_executable_file(script_path):
        gbd_script_path = script_path
        return

    error_out("Can't find grab-boot-data.sh on system!")

def gen_report_data(method, baseline_path, results_path):
    report_data = "#"*70  + "\n" + \
        "=== Results report for optimization method '%s' ===\n" % method.name

    # compare a few summary items:
    base_compare_list = ["time_to_init", "SYSTEMD_KERNEL_USECS", "SYSTEMD_USERSPACE_USECS"]

    compare_list = base_compare_list + method.get_compare_list()

    # Then compare some method-specific items:
    header = "-- Individual item comparisons --\n"
    # make a list of items to compare
    compare_str = " ".join(compare_list)

    cmd = "boot-data compare %s -f %s %s" % (baseline_path, results_path,
                                          compare_str)
    status, output = getstatusoutput(cmd)

    report_data += header + output + "\n\n"

    header = "-- Boot-data diff of baseline and results --\n"
    cmd = "boot-data diff %s -f %s" % (baseline_path, results_path)
    status, output = getstatusoutput(cmd)
    report_data += header + output + "\n\n"

    # FIXTHIS - raw diff is crude, let's omit for now
    #header = "-- Raw diff of baseline and results --\n"
    #cmd = "diff -u %s %s" % (baseline_path, results_path)
    #status, output = getstatusoutput(cmd)
    #report_data += header + output

    return report_data

# generate a report from existing run artifacts
def generate_report(report_run_id, method, target, artifact_dir, saved_args):
    global run_prefix

    if report_run_id.startswith("run-"):
        report_run_id = report_run_id[4:]

    if len(report_run_id) != 6:
        error_out("Invalid run-id.  It must be a 6-digit number.")

    run_prefix = "run-%s-" % report_run_id
    artifact_prefix = artifact_dir + "/" + run_prefix

    report_path = artifact_prefix + "report.txt"

    if os.path.exists(report_path):
        print("Report '%s' already exists" % report_path)
        response = input("OK to overwrite? [Y/n] ")
        if not response == "Y":
            print("Report Generation cancelled!")
            sys.exit(0)

    # find file paths
    candidates = os.listdir(artifact_dir)
    baseline_prefix = run_prefix + "baseline"
    results_prefix = run_prefix + "results"
    baseline_path = ""
    results_path = ""
    for candidate in candidates:
        if candidate.startswith(baseline_prefix):
            baseline_path = artifact_dir + "/" + candidate
        if candidate.startswith(results_prefix):
            results_path = artifact_dir + "/" + candidate

    if not baseline_path:
        error_out("Cannot find baseline boot-data file. Possible invalid run-id '%s'" % report_run_id)
    if not results_path:
        error_out("Cannot find results boot-data file. Possible invalid run-id '%s'" % report_run_id)

    # clean up saved_args - remove '-r <run-id>'
    arg_pos = saved_args.index("-r")
    del saved_args[arg_pos + 1]
    del saved_args[arg_pos]

    rheader = report_header(run_prefix[:-1], target.name, saved_args)
    report_data = gen_report_data(method, baseline_path, results_path)

    # False = do not append
    log_to_report(artifact_prefix, rheader + report_data, False)

    print("Report data is in: '%s'" % report_path)
    sys.exit(0)


def main():
    global debug
    global verbose
    global run_prefix, kernel_id

    saved_args = sys.argv[1:]

    script_dir = os.path.dirname(os.path.realpath(sys.argv[0]))
    patch_dir = script_dir + "/patches"
    find_gbd_script_path(script_dir)

    # allow error-free piping to other command line utilities (like 'head')
    signal(SIGPIPE, SIG_DFL)

    # parse command line arguments
    target = None
    method = None
    method_name = None
    artifact_dir = ""
    artifact_dir_created = False
    override_kernel_dir = ""
    do_list = False
    do_gen_report = False

    if "-h" in sys.argv or "--help" in sys.argv:
        usage()

    if "-V" in sys.argv or "--version" in sys.argv:
        print("boot-time-wizard version v%d.%d.%d" % VERSION)
        sys.exit(0)

    verbose = get_boolean_opt('-v')
    debug = get_boolean_opt('--debug')
    do_list = get_boolean_opt('-l')

    if "-t" in sys.argv:
        target_name = get_opt_with_arg('-t')
        try:
            # this can take some time
            target = target_class(target_name)
        except ValueError:
            error_out("'%s' is not a recognized target" % target_name)

    if "-d" in sys.argv:
        artifact_dir = get_opt_with_arg('-d')
        if not os.path.isdir(artifact_dir):
            error_out("'%s' does not exist: Invalid argument for -d" % artifact_dir)
        # make artifact_dir absolute, since we might change dirs
        artifact_dir = os.path.abspath(artifact_dir)

    if "-k" in sys.argv:
        override_kernel_dir = get_opt_with_arg('-k')
        if not os.path.isdir(override_kernel_dir):
            error_out("'%s' does not exist: Invalid argument for -k" % override_kernel_dir)
        if not os.path.isfile(override_kernel_dir + "/MAINTAINERS"):
            error_out("Missing 'MAINTAINERS'; '%s' does not not appear to be a kernel source directory" % override_kernel_dir)

    if "-m" in sys.argv:
        method_name = get_opt_with_arg('-m')

    if "-r" in sys.argv:
        report_run_id = get_opt_with_arg('-r')
        do_gen_report = True

    # done parsing command line

    # do more initialization
    kernel_dir = ""
    if override_kernel_dir:
        kernel_dir = override_kernel_dir
    else:
        # presumably target has a KERNEL_SRC setting
        if target:
            kernel_dir = target.KERNEL_SRC

    # try to auto-detect the kernel source directory
    if not kernel_dir or not os.path.isfile(kernel_dir + "/MAINTAINERS"):
        # try to find one
        if os.path.isfile("MAINTAINERS"):
            kernel_dir = "."
        if os.path.isfile("linux/MAINTAINERS"):
            kernel_dir = "linux"
        if kernel_dir:
            print("Using '%s' as the kernel source dir" % kernel_dir)
        else:
            error_out("No kernel source dir specified.")

    kernel_dir = os.path.abspath(kernel_dir)
    dprint(f"{kernel_dir=}")

    # if no artifact-dir specified, create one in .
    if not artifact_dir:
        artifact_dir = "btw-artifacts"
        try:
            os.mkdir(artifact_dir)
            artifact_dir_created = True
        except FileExistsError:
            pass

    # make artifact_dir absolute
    artifact_dir = os.path.abspath(artifact_dir)
    dprint(f"{artifact_dir=}")

    # fixup target with extra info and overrides
    if target:
        target.artifact_dir = artifact_dir
        target.patch_dir = patch_dir
        # warn if we're about to use an unexpected kernel_dir
        if target.KERNEL_SRC != kernel_dir:
            wprint("Overriding target's KERNEL_SRC dir ('%s') with '%s'" % (target.KERNEL_SRC, kernel_dir))
        target.KERNEL_SRC = kernel_dir

    vprint("Initializing methods...")
    methods = init_methods(kernel_dir)

    # handle '-l' before making artifact dir, it's just informational
    if do_list:
        list_methods(methods, target)
        sys.exit(0)

    # OK - we're testing an optimization.  This requires a target.
    if not target:
        error_out("You must specify a target to test optimization. Use -h for help.")

    # check for valid method_name
    if method_name:
        if method_name not in methods:
            error_out("Invalid argument for -m: method '%s' is not recognized (use -l to list)" % method_name)
        else:
            method = methods[method_name]

    # OK - we're doing an optimization run
    # set the run_prefix and kernel_id
    random.seed()
    rnd = random.randint(0, 999999);
    run_prefix = "run-%06d-" % rnd
    run_count = 1
    kernel_id = "%06d-%d" % (rnd, run_count)
    artifact_prefix = artifact_dir + "/" + run_prefix
    dprint(f"{artifact_prefix=}")
    target.artifact_prefix = artifact_prefix

    # generate report from results files, without running a test
    if do_gen_report:
        print(f"{saved_args=}")
        generate_report(report_run_id, method, target, artifact_dir, saved_args)

    if method:
        # near as I can tell, this is never used (use the one on the 'target' instead')
        #method.artifact_prefix = artifact_prefix

        print("== Instrumenting target: %s, for method '%s'" % (target.name, method.name))
        method.instrument_target(target)

        if method.needs_kbuild:
            vprint(" - Building and installing with instrumentation...")

            # set kernel name we can check!!
            status = target.rebuild_and_install("btw-instr")
            if not status:
                eprint("Problem rebuilding after instrumentation!")

        #TRB_wait_for_input("Is instrumented kernel on the board!!")

        try_one_method(method, target, artifact_prefix)

        print("== De-Instrumenting target")
        method.de_instrument_target(target)

        if method.needs_kbuild:
            # get back to baseline (previous) kernel (if needed)
            # rebuild kernel
            target.clear_localversion()
            print(" - Rebuilding and installing kernel...")
            status = target.rebuild_and_install()

        # reboot one last time to return to baseline kernel and settings
        target.ttc("reboot")

        # save results to a report file
        rheader = report_header(run_prefix[:-1], target.name, saved_args)
        log_to_report(artifact_prefix, rheader + method.results_txt)

        #method.show_results()
        print("Results are in the report file")
    else:
        tune_boot_time(methods, target, artifact_prefix)

    # FIXTHIS - support an option to clean up files (in artifact_dir)
    print("Data files for this run are in '%s' with the prefix '%s'" % (artifact_dir, run_prefix))

    # FIXTHIS - need to fully reset target??
    # that would include restore_build_config, build, kinstall

    sys.exit(0)

if __name__ == "__main__":
    main()
